name: CI
on:
  pull_request:
    branches: [ main ]
jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - run: |
        gem install bundler
        bundle
        chmod +rw utapri.json
        chmod +rw utapri.yml
        ruby sort_json.rb
        git config user.name "$(git log -1 --pretty=format:"%cn")"
        git config user.email "git log -1 --pretty=format:"%ce""
        git add utapri.yml
        git commit -m ":shower: Sort utapri.yml"
        git add utapri.json
        git commit -m ":shower: Sort utapri.json"
        git push "https://${{ secrets.PERSONAL_GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}" ${GITHUB_REF##*/}
