name: CI
on:
  pull_request:
    branches: [ main ]
jobs:
  sort:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - run: |
        gem install bundler
        bundle
        chmod +rw utapri.json
        chmod +rw utapri.yml
        ruby sort_json.rb
        scripts/commit.sh
      env:
        PERSONAL_GITHUB_TOKEN: secrets.PERSONAL_GITHUB_TOKEN
